### ISSUE TITLE
RS310P

### ISSUE THREAD

**Issue by snax44** [hobbyquaker/hanmatek-hm310p#2]
Hi,

Thanks for this software.
I am trying to use it with ROCKSEED rs310p.

Firstly I cannot click on "close" button when I put the serial port /dev/ttyUSB1.
Is it because it's not exactly the same powersupply ?

Thanks in advance.
Maël

**Comment by bilalh96** [comment]
Hi,
No, the error can be corrected, you should check the solution in the other issue thread. you need to actually makes slight changes in the code. its all mentioned there ;)

**Comment by Gandohr** [comment]
> Hi,
> No, the error can be corrected, you should check the solution in the other issue thread. you need to actually makes slight changes in the code. its all mentioned there ;)

Thats all based on Windows. those files do not exist on OSX
at least I can't find them, maybe point me to the right folders?

**Comment by lee3521** [comment]
I am struggling with this as well.  Running on Linux Mint.  I was thinking the port config would be stored in a flat text file I could manually edit, but so far, I have not managed to find it.

**Comment by snax44** [comment]
Actually we need to change it in the source code. And then compile it again.
I'm also using Linux, I tried to compile but unfortunately something wrong happened. 
I gave up because I don't need it any more, maybe in few months...

@bilalh96 thanks for your answer
